site_name: Bloomberg Tech Lab
nav:
  - Home: index.md
  - Backend: backend.md
  - Frontend: frontend.md
  - Interview Question Prompt: api-question-prompt.md
  - Resources:
    - Overview: resources/overview.md
    - Redis Basics: resources/redis-basics.md
    - Git Basics: resources/git-basics.md
    - Python Basics: resources/python-basics.md
    - Docker Basics: resources/docker-basics.md
    - HTML Basics: resources/html-basics.md
    - React Basics: resources/react-basics.md
    - NextJs Basics: resources/next-js-basics.md
theme: readthedocs
